# https://github.com/release-drafter/release-drafter
name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |

  ## âš ï¸ Breaking Changes
  - Breaking 1: Description of breaking change 1.

  ## What's changed
  $CHANGES

  ### New Features âš¡
  - Feature 1: Description of feature 1.

  ### Enhancements ðŸ”¥
  - Enhancement 1: Description of Enhancement 1.

  ### Fixes ðŸ”§
  - Fix 1: Description of bug fix 1.

  ### Maintenance âš™ï¸
  - This
  - That

  ### Other Changes
  - Other change 1: Description of other change 1.
