"""Bandcamp API - standalone async client for Bandcamp."""

from .client import (
    TRALBUM_TYPE_ALBUM,
    TRALBUM_TYPE_TRACK,
    BandcampAPIClient,
    BandcampAPIError,
    BandcampBadQueryError,
    BandcampMustBeLoggedInError,
    BandcampNotFoundError,
    BandcampRateLimitError,
    BandcampUnexpectedResponseError,
)
from .models import (
    BCAlbum,
    BCArtist,
    BCTrack,
    CollectionItem,
    CollectionSummary,
    FanItem,
    FeedBandInfo,
    FeedFanInfo,
    FeedResponse,
    FeedStory,
    FeedTrack,
    FollowingItem,
    SearchResultAlbum,
    SearchResultArtist,
    SearchResultItem,
    SearchResultTrack,
)

__all__ = [
    "TRALBUM_TYPE_ALBUM",
    "TRALBUM_TYPE_TRACK",
    "BCAlbum",
    "BCArtist",
    "BCTrack",
    "BandcampAPIClient",
    "BandcampAPIError",
    "BandcampBadQueryError",
    "BandcampMustBeLoggedInError",
    "BandcampNotFoundError",
    "BandcampRateLimitError",
    "BandcampUnexpectedResponseError",
    "CollectionItem",
    "CollectionSummary",
    "FanItem",
    "FeedBandInfo",
    "FeedFanInfo",
    "FeedResponse",
    "FeedStory",
    "FeedTrack",
    "FollowingItem",
    "SearchResultAlbum",
    "SearchResultArtist",
    "SearchResultItem",
    "SearchResultTrack",
]
